# Generated by Django 3.2.4 on 2021-09-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('booking_number', models.CharField(max_length=64)),
                ('seat_number', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('teenager', models.IntegerField()),
                ('kid', models.IntegerField()),
                ('movie_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movietheater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
