# Generated by Django 3.2.5 on 2021-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210918_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='teenager',
            field=models.IntegerField(null=True),
        ),
    ]
